### ISSUE TITLE
Controllers on other languages than Go

### ISSUE THREAD

**Issue by galvesribeiro** [kubernetes/sample-controller#12]
Hello,

I wonder if the controllers API is only available if using Go SDK/Client.

Are all APIs used in this Go sample available on API Server so we can write on our own languages the Controllers?

In case of yes, can someone point to the right doc so I can read more about it?

Thank you! Really appreciate any help.

**Comment by nikhita** [comment]
There are clients available in other languages as well: https://github.com/kubernetes-client.

> In case of yes, can someone point to the right doc so I can read more about it?

I am not entirely sure if we have docs for those (if we don't, we should make sure we have them). Maybe @tamalsaha or @enisoc know?

**Comment by galvesribeiro** [comment]
THanks @nikhita Those clients are to talk to the API Server. I'm OK as we have our API client hand made here. The point is that I'm not seeing any docs neither any endpoint for custom controllers. 

All I find is like this sample that technically implement a sample controller. I just don't know what it (controllers) does and how to proper implement then.

I'm trying to evaluate all the extension point and see what brings value to our system.

**Comment by nikhita** [comment]
> I just don't know what it (controllers) does

I personally like @ericchiang's slides on this. https://talks.godoc.org/github.com/ericchiang/go-1.8-release-party/kubernetes-controllers.slide#7

To quote that, a controller is a "Fancy Kubernetes-ism for a client that talks to the API in a loop." It looks at the current state of the object and tries to bring it to the desired state (by updating, deleting, etc). Example: ReplicationController is used to ensure that correct number of replicas is running.

In case of a CRD/custom resource which does _not_ interact with a controller, it just helps you to store and receive unstructured data.

By using a controller, you can "control" (for the lack of a better term) the custom resources. For example, depending on certain conditions, you can update the status of whatever is being managed by the controller (this is what `sample-controller` does).

This custom controller is also commonly called "operator pattern". https://coreos.com/blog/introducing-operators.html
There are many talks and slides out there about this. :)

**Comment by galvesribeiro** [comment]
Oh!! Thank you @nikhita 

Looks like I'll have usage for it. Now just need to find where in the API Server are the endpoints to create it.

I'm already using CRDs to store/read some cluster metadata of Orleans (https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes). Now I'm working in another system and looks like the controller is something doable for me.

Thank you very much! Will close the issue for now.
