### ISSUE TITLE
Simple example with detailed instructions

### ISSUE THREAD

**Issue by vncntvandriessche** [kubernetes/sample-controller#13]
The controller is complex for the untrained eye, the required steps aren't very clear to me. It would be nice to have a more simple example, with some steps to follow along the development and decision making during it's progress.

This is how far I've gotten:
According to my understanding a controller for a `CustomResource` is built using the following algorithm:

# 1. Create the following directory structure:
```
.
├── Gopkg.lock
├── Gopkg.toml
├── README.md
├── artifacts
│   ├── example1.yaml
│   ├── example2.yaml
│   ├── [...]
│   └── example-crd.yaml
├── generator
│   ├── custom-boilerplate.go.txt
│   ├── update-codegen.sh
│   └── verify-codegen.sh
├── main.go
└── pkg
    └── apis
        └── samplecontroller/
            ├── register.go
            └── v1alpha1
                ├── doc.go
                ├── register.go
                └── types.go
```

Next up, I'll try to explain the contents of each required file in the above skeleton...

## ./Gopkg.toml

Example input:

```
required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.8"

# goland/dep does not follow k8s.io/code-generator's Godeps.json and gengo's master
# version does not work with release-1.8 k8s.io/code-generator. So we have to
# override it.
[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"
```

The gist of this file is that it will allow you to generate the required code using the [code-generator-project](https://github.com/kubernetes/code-generator).

## ./artifacts/example1.yaml

```
apiVersion: samplecontroller.k8s.io/v1alpha1
kind: Foo
metadata:
  name: example-foo
spec:
  deploymentName: example-foo
  replicas: 1
```

This is basically the same type of file you'd create for any other resource, but with a different api-endpoint. Refer to the explanation for the `./artifacts/example-crd.yaml `-file.

## ./artifacts/example-crd.yaml

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Foo
    singular: foo
    plural: foos
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```

This file adds a custom resource at apiVersion `samplecontroller.k8s.io`, version `v1alpa1`, kind: `Foo`.
[More info](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/)

## ./generator/update-codegen.sh

```
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT=$(dirname ${BASH_SOURCE})/..
CODEGEN_PKG=${CODEGEN_PKG:-$(cd ${SCRIPT_ROOT}; ls -d -1 ./vendor/k8s.io/code-generator 2>/dev/null || echo ../code-generator)}

# generate the code with:
# --output-base    because this script should also be able to run inside the vendor dir of
#                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
#                  instead of the $GOPATH directly. For normal projects this can be dropped.
${CODEGEN_PKG}/generate-groups.sh "deepcopy,client,informer,lister" \
  k8s.io/sample-controller/pkg/client k8s.io/sample-controller/pkg/apis \
  samplecontroller:v1alpha1 \
  --output-base "$(dirname ${BASH_SOURCE})/../../.."

# To use your own boilerplate text append:
#   --go-header-file ${SCRIPT_ROOT}/hack/custom-boilerplate.go.txt
```

This script allows you to generate the required code too create functionality for the most common actions; In this case: `"deepcopy,client,informer,lister"`, which are common components for a `CustomResourceController`.

` k8s.io/sample-controller/pkg/client k8s.io/sample-controller/pkg/apis`
Should be swapped by your projects' "apis"-folder location.

`samplecontroller:v1alpha1` should be edited into `<yoursamplecontroller.com:youversion>`.

## ./generator/verify-codegen.sh

This script is primarily used for CI/CD pipelines, as it invokes the previous script and checks to see if there would have been any changes.

## ./main.go, ./controller.go

This is where the actual controller should live. It's responsibility would generally be (in case of a `CustomResourceController` to read events for the `CustomResource` and invoke actions based on these events.

> For example: If I were to create a `CustomResource` called `Staging` and wanted to create some deployments based off-of some variables within this resource. I'd need a controller listening for events (`Watch`) and performing orchestration/cleanup when required.

Some thoughts:
- You'll need to handle exitting properly through several threads, as we need to stop some loops from running indefinitely
- You'll need to implement workers, as you don't want events to wait for a deployment orchestration-operation to finish
- Somehow you'll need to start watching all newly orchestrated components for changes as wel, to ensure they get re-orchestrated when something happens to them
- ... (whatever many many options I have probably missed up until now)

... Then again, there might be a lot simpler ways to approach this, but these weren't clear yet to me.

## ./pkg/apis/samplecontroller/v1alpha1/register.go

```
package samplecontroller

const (
	GroupName = "samplecontroller.k8s.io"
)
```

Package should match the directory name used within apis & the group name should be adjusted to the name set in the `CustomResourceDefinition`.

## ./pkg/apis/samplecontroller/v1alpha1/types.go

```
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Foo is a specification for a Foo resource
type Foo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FooSpec   `json:"spec"`
	Status FooStatus `json:"status"`
}

// FooSpec is the spec for a Foo resource
type FooSpec struct {
	DeploymentName string `json:"deploymentName"`
	Replicas       *int32 `json:"replicas"`
}

// FooStatus is the status for a Foo resource
type FooStatus struct {
	AvailableReplicas int32 `json:"availableReplicas"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// FooList is a list of Foo resources
type FooList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Foo `json:"items"`
}
```

This is a bit harder to explain but to put it bluntly: You create a golang representation of the data described in the `CustomResourceDefinition`, with the comments starting with `// +k8s:` depicting a special role:
They tell the `code-generator` what code to generate.

The package here should match the version chosen 

## ./pkg/apis/samplecontroller/v1alpha1/doc.go

```
// +k8s:deepcopy-gen=package

// Package v1alpha1 is the v1alpha1 version of the API.
// +groupName=samplecontroller.k8s.io
package v1alpha1
```

In this case, this file serves solely to set the general settings for the `code-generator` it
- sets the group name for the generated files
- tells the `deepcopy-gen`erator to generate deep copy methods for each type in that package (unless the parameters above that type override it)

## ./pkg/apis/samplecontroller/register.go

```
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	samplecontroller "k8s.io/sample-controller/pkg/apis/samplecontroller"
)

// SchemeGroupVersion is group version used to register these objects
var SchemeGroupVersion = schema.GroupVersion{Group: samplecontroller.GroupName, Version: "v1alpha1"}

// Kind takes an unqualified kind and returns back a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

var (
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)
	AddToScheme   = SchemeBuilder.AddToScheme
)

// Adds the list of known types to Scheme.
func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(SchemeGroupVersion,
		&Foo{},
		&FooList{},
	)
	metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
	return nil
}
```

I'm not sure what this file exactly fulfils but I know it is important, you'll need to ensure the:
- package name is correct (matches the version in the `CustomResourceDefinition`)
- the imports are relative to your project, not `samplecontroller`
- `var SchemeGroupVersion = schema.GroupVersion{Group: samplecontroller.GroupName, Version: "v1alpha1"}`'s `"v1alpha1"` should also be changed to match the version in the `CustomResourceDefinition`

# 2. Generate the required code

> Allright, this is a fine time to create a commit to run back to when everything hits the fan.

## Fetch dependencies

```
dep ensure
```

## Generate required libraries based off-of your types

```
./generator/update-codegen.sh
```

## Fetch dependencies
I'm not even sure this is actually always required, but I just like doing it...

```
dep ensure
```

# 3. Create the Controller's logic

Now that all the required code has been generated we've got ourselves some nice options to perform some routine tasks:

- `./pkg/client/clientset/versioned/typed/samplecontroller/v1alpha1/samplecontroller_client.go` which will act as our goto-structure to access any api-endpoint related to the `CustomResource` we created.
- `./pkg/client/clientset/versioned/typed/samplecontroller/v1alpha1/foo.go` which will add the `.Foo("<supply a namespacehere>")` which in turn supplies an interface to operations like:
  - List
  - Get
  - Watch
  - ...

# End
That's it for now! I'm kind of stuck after managing to really simply listening for `added` events and printing the contents of my type.
I want to be able to do a lot more, like create complete environments as a result of a `CustomResource` being added / altered etc... But I'm not there yet. _Any_ help is _greatly_ appreciated. ;)

Please note that I am not fully fluent in golang nor am I a programmer (operations). I just want to be able to understand en grasp the usefulness of this awesome project.

**Comment by nikhita** [comment]
We can probably mention something like this in the README. :+1: 

/cc @sttts @munnerz

**Comment by vncntvandriessche** [comment]
@nikhita Is there any *resource/channel/...* you'd suggest gathering information to continue from the point where I stopped in the above document. This is where it gets very hard for me. At least, it is if I want to follow the examples provided.

**Comment by devdattakulkarni** [comment]
@vncntvandriessche Good writeup.

I have recently written an article that explains under-the-hood details of the client-go machinery. 
Check it out here:
https://medium.com/@cloudark/kubernetes-custom-controllers-b6c7d0668fdf

Hopefully it helps!

@nikhita: Would be interested in your thoughts about the article as well.

**Comment by sttts** [comment]
@devdattakulkarni would you mind to contribute the figure from your blog to the controller sample README?

![controllers](https://cdn-images-1.medium.com/max/1600/1*dmvNSeSIORAMaTF2WdE9fg.jpeg)

**Comment by devdattakulkarni** [comment]
@sttts I would be happy to contribute the figure. And if required the write-up too. Let me know the process. Should I just open a PR with modifications to the README? Also, is there any specific directory to put the figure and then link its path in the README?

**Comment by sttts** [comment]
@devdattakulkarni 👍, just create a PR against the README in the main kubernetes repo.

**Comment by devdattakulkarni** [comment]
@sttts Cool. Will do that.

One more question -- when you say README in main kubernetes repo, do you mean:
https://github.com/kubernetes/kubernetes

or you mean:
https://github.com/kubernetes/sample-controller

**Comment by nikhita** [comment]
@devdattakulkarni This one: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-controller/README.md. :)

**Comment by vncntvandriessche** [comment]
@devdattakulkarni Thanks for sharing the article. I read it and it provides a lot of insights I was still missing.
I'll start hacking soon thanks to your help!

**Comment by devdattakulkarni** [comment]
@nikhita Thanks :)

@sttts https://github.com/kubernetes/kubernetes/pull/62563

@vncntvandriessche :)

**Comment by devdattakulkarni** [comment]
@sttts @nikhita The PR https://github.com/kubernetes/kubernetes/pull/62563 has passed all the tests. Let me know if anything else is required.

**Comment by vncntvandriessche** [comment]
@barry-schneider Those lines just ensure no one forgets to change `yoursamplecontroller.com` and the version set in your custom resource is what you've set it to be.

These are parameters you can choose for yourself and should be changed everywhere once customised.

**Comment by esnunes** [comment]
Do you know why we need to manually create the `pkg/apis/samplecontroller/v1alpha1/register.go` file. The generator depends on `Resource` func, looks like this code could be generate automatically too. Is there a reason not to automatically generate it?

**Comment by esnunes** [comment]
@vncntvandriessche sorry, it is manually created. I was just wondering what is the reason why it is not generated automatically.

**Comment by nikhita** [comment]
https://github.com/kubernetes/sample-controller/blob/master/docs/controller-client-go.md explains the reasoning but I guess we still need documentation in a "steps form". Step 1,.. Step 2,...

**Comment by nikhita** [comment]
> I think it actually could be generated, as all info that's required seems to be available from the custom resource?

@sttts Wdyt about generating `register.go` too?

**Comment by sttts** [comment]
We probably could. We might need some more tags (which are the `runtime.Object` types to register in the scheme?). Also, aren't there small differences depending on whether you have custom conversions or defaulters?

**Comment by devdattakulkarni** [comment]
@nikhita: Recently I had created a list of steps to serve as a quick reference of all the things that need to be done to create a custom controller. There are available here: 

https://github.com/cloud-ark/kubeplus/issues/14

Were you thinking something along these lines?

Currently the explanation on the steps is sparse but that can be fixed. If you think this might be useful, I will be happy to contribute the steps.

**Comment by cmoulliard** [comment]
> This is how far I've gotten

Have you created a github repo containing your code + instructions ? @vncntvandriessche

**Comment by vncntvandriessche** [comment]
@cmoulliard I'm afraid not, if I get around to it, I'll give a nudge here!
