### ISSUE TITLE
govet error: "literal copies lock value from fakePtr"

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/sample-controller#16]
From https://github.com/kubernetes/ingress-gce/pull/163.

Using the auto generating scripts in hack/ with golang 1.10.1 and hit below error when running govet:
```
# k8s.io/ingress-gce/pkg/serviceextension/client/clientset/versioned/fake
pkg/serviceextension/client/clientset/versioned/fake/clientset_generated.go:56: literal copies lock value from fakePtr: k8s.io/ingress-gce/vendor/k8s.io/client-go/testing.Fake
```

It seems that is also the case in this repo:
https://github.com/kubernetes/sample-controller/blob/9d231f2a2a34c4a866e80465eb50fc7b2806eddf/pkg/client/clientset/versioned/fake/clientset_generated.go#L44-L56

Should we fix the generated code or am I missing something?

**Comment by MrHohn** [comment]
Oh seems like a fix is pending: https://github.com/kubernetes/kubernetes/pull/60584

**Comment by nikhita** [comment]
/remove-lifecycle stale

PR is open
