### ISSUE TITLE
Getting issue while fetching the  sample-controller

### ISSUE THREAD

**Issue by rahulkrishnanfs** [kubernetes/sample-controller#17]
When I do  $go get github.com/kubernetes/sample-controller

I am getting the following issue 

github.com/kubernetes/sample-controller
src\github.com\kubernetes\sample-controller\controller.go:102:26: cannot use "github.com/kubernetes/sample-controller/vendor/k8s.io/client-go/kubernetes/scheme".Scheme (
type *"github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Scheme) as type *"k8s.io/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime"
.Scheme in argument to "k8s.io/sample-controller/pkg/client/clientset/versioned/scheme".AddToScheme
src\github.com\kubernetes\sample-controller\controller.go:292:27: cannot use foo (type *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo) as type "githu
b.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery
/pkg/apis/meta/v1".IsControlledBy:
        *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo does not implement "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/api
s/meta/v1".Object (wrong type for GetCreationTimestamp method)
                have GetCreationTimestamp() "k8s.io/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
                want GetCreationTimestamp() "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
src\github.com\kubernetes\sample-controller\controller.go:294:19: cannot use foo (type *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo) as type "githu
b.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to c.recorder.Event:
        *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo does not implement "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/run
time".Object (wrong type for DeepCopyObject method)
                have DeepCopyObject() "k8s.io/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object
                want DeepCopyObject() "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object
src\github.com\kubernetes\sample-controller\controller.go:320:18: cannot use foo (type *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo) as type "githu
b.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to c.recorder.Event:
        *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo does not implement "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/run
time".Object (wrong type for DeepCopyObject method)
                have DeepCopyObject() "k8s.io/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object
                want DeepCopyObject() "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/runtime".Object
src\github.com\kubernetes\sample-controller\controller.go:404:29: cannot use foo (type *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo) as type "githu
b.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery
/pkg/apis/meta/v1".NewControllerRef:
        *"k8s.io/sample-controller/pkg/apis/samplecontroller/v1alpha1".Foo does not implement "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/api
s/meta/v1".Object (wrong type for GetCreationTimestamp method)
                have GetCreationTimestamp() "k8s.io/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
                want GetCreationTimestamp() "github.com/kubernetes/sample-controller/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
src\github.com\kubernetes\sample-controller\main.go:56:46: cannot use cfg (type *"github.com/kubernetes/sample-controller/vendor/k8s.io/client-go/rest".Config) as type *
"k8s.io/sample-controller/vendor/k8s.io/client-go/rest".Config in argument to versioned.NewForConfig

**Comment by cmoulliard** [comment]
I also get the same issue even if the env vars are well defined

```
o env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dabou/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dabou/Code/go-workspace"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
