### ISSUE TITLE
What does operating in-cluster mean under running section of readme

### ISSUE THREAD

**Issue by barry-schneider** [kubernetes/sample-controller#18]
Please clarify what this mean: 

https://github.com/kubernetes/sample-controller/blob/master/README.md#running
```
# assumes you have a working kubeconfig, not required if operating in-cluster
$ go run *.go -kubeconfig=$HOME/.kube/config
```

- What is not required?
- How would you operate in-cluster?

**Comment by radu-munteanu** [comment]
You got the answer in another issue you posted. There's a function that checks if it can take the config from the cluster, if run within a pod.
