### ISSUE TITLE
How to deploy controller into the cluster

### ISSUE THREAD

**Issue by barry-schneider** [kubernetes/sample-controller#19]
I am a bit confused about where the custom controller is being run from. I had assumed that the customer controller would run within the cluster, just as the deployment controller does, watching and taking action. But based on my reading the custom control is client side and lives outside of kubernetes. I have have seen one [example](https://github.com/CrunchyData/postgres-operator) running the custom control client within a Pod in the cluster. But I could not figure out the specific code to make this work.

**Comment by barry-schneider** [comment]
I found a few examples

[Kubeless](https://github.com/kubeless/kubeless/) - use a Custom Resource Definition to be able to create functions as custom kubernetes resources. Then run an in-cluster controller that watches these custom resource - could this technique be incorporated into the sample?

[kubewatch](https://github.com/bitnami-labs/kubewatch) - A kubewatch container will be created along with kubectl sidecar container in order to reach the API server.

**Comment by nikhita** [comment]
> Then run an in-cluster controller that watches these custom resource - could this technique be incorporated into the sample?

Not sure I follow, can you elaborate on how the in-cluster controller works in this case?

/cc @sttts @munnerz

**Comment by sttts** [comment]
The example uses `BuildConfigFromFlags` which in turn calls `InClusterConfig` (https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/client_config.go#L553). So it should work in a pod. If it doesn't, it's a bug.

**Comment by radu-munteanu** [comment]
All controllers can be run outside K8s or inside, as an unique pod deployed on master. They use API calls to communicate with the cluster. For testing purposes, it's just easier to use it locally, rather than package it into a container and the run it as a pod.
