### ISSUE TITLE
Create json-schema for use in the CRDs from the go types.

### ISSUE THREAD

**Issue by erictune** [kubernetes/sample-controller#2]
CRDs support json-schema schemas.  These CRDs don't have them.  It would be nice to show how to add them, initially maintained in parallel with the Go types, and then later generated from the Go types (pkg/apis).

**Comment by erictune** [comment]
xref https://github.com/kubernetes/code-generator/issues/28

**Comment by nikhita** [comment]
WIP in https://github.com/kubernetes/kube-openapi/pull/37
