### ISSUE TITLE
Can't run the test : go run: cannot run *_test.go files (controller_test.go)

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes/sample-controller#23]
This command is failing when it is executed

```
go get k8s.io/sample-controller
cd $GOPATH/src/k8s.io/sample-controller
go build .
./hack/update-codegen.sh 
go run *.go -kubeconfig=$HOME/.kube/config
go run: cannot run *_test.go files (controller_test.go)
```

We can run the test using nevertheless this command

```
go test .
ok      k8s.io/sample-controller        0.035s
```

**Comment by nikhita** [comment]
Thanks for reporting this, @cmoulliard. Fix in https://github.com/kubernetes/kubernetes/pull/65609.

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/65609, thanks to @CaoShuFeng! :)

/close
