### ISSUE TITLE
Forgetting event upon processing functional?

### ISSUE THREAD

**Issue by NoahElzein** [kubernetes/sample-controller#25]
I have designed a Postgres Controller based on the Sample controller. processNextWorkItem is exactly the same in my case as the sample controller. For some reason events keep looping through my queue even after being processed which leads me to believe they may not be correctly being forgotten from the queue. My synchandler also takes the same and I just added the logic for handling Postgres objects. By inserting some print statements I am able to confirm that it always exits successfully and upon returning to the processNextWorkItem function it also funishes successfully and calls the forget function. But for some reason the event is never forgotten and the next time processNextWorkItem is called it comes up with the same event.

**Comment by nikhita** [comment]
@NoahElzein Can you share a link to your code?

Easier to figure out the issue then. :)

**Comment by yue9944882** [comment]
i suppose @NoahElzein 's controller keeps receiving duplicated events assuming your code is correct  💯, plz show us some more code for further troubleshooting as @nikhita suggests.

**Comment by NoahElzein** [comment]
Hello, 

Over the recent few days I found out it was an issue in my code. Specifically in the Update Func of my EventHandler, I was incorrectly checking the state. I got it to work normally now and the events are being forgotten correctly.

Apologies for opening up the issue and thank you for your help!

**Comment by nikhita** [comment]
@NoahElzein Glad to hear you got it working. Thanks for circling back and updating the issue!
