### ISSUE TITLE
Switch dependency management to `dep`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/sample-controller#27]
@sttts @nikhita WDYT of switching to `dep`?  If you are ok with it I can open a PR.

**Comment by justinsb** [comment]
I have found vgo (aka go) to be great.   Perhaps now is not the time to adopt dep?

**Comment by pwittrock** [comment]
@justinsb Looks like this is published from staging, and that may be why it hasn't been migrated yet.  FWIW [the vgo doc](https://github.com/golang/go/wiki/vgo#current-state) says to use `dep` for production workloads.

**Comment by nikhita** [comment]
> Looks like this is published from staging, and that may be why it hasn't been migrated yet. 

Yeah, I don't think we can move to dep unless k/k does. I'll close this in favour of https://github.com/kubernetes/kubernetes/issues/63607, which talks about using vgo for staging. Please reopen if needed.

/close
