### ISSUE TITLE
Move sample-controller out of staging

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/sample-controller#28]
@nikhita @sttts WDYT of moving this out of staging?  None of the projects written by consumers of sample-controller will live in staging, so it might be nice to have this match their reality.

**Comment by sttts** [comment]
Who will maintain it outside of k/k? I.e. rebase it to latest client-go each release. In k/k we basically get this for free.

**Comment by nikhita** [comment]
@pwittrock Yeah, rebasing it to the latest staging repos (api, apimachinery, client-go, code-generator...) is a huge trouble :( and that's the reason we have it in staging. Also, that's why repos like cluster-bootstrap, cloud-provider are being added into staging today.

Closing this issue. Please reopen if needed.
/close

**Comment by DirectXMan12** [comment]
@nikhita @sttts we can probably maintain this as part of the kubebuilder/controller-runtime/controller-tools ecosystem.  We probably don't want to actually encourage people to write controllers from scratch like this, copying and pasting all this code around.

This project already falls under the [server-sdk subproject](https://github.com/kubernetes/community/blob/master/sig-api-machinery/README.md), which also is responsible for KB, CR, and CT, so it seems reasonable to have the KB maintainers maintain the sample as a consumer of CR/CT.

WDYT?

**Comment by sttts** [comment]
It also serves the purpose of test bed for k8s.io/code-generator and other machinery.

And with many people still following this style intentionally, there is value to keep it. I would be fine with some links in the readme to get to know about the other controller building tools.

**Comment by DirectXMan12** [comment]
> And with many people still following this style intentionally, there is value to keep it

If people (outside the SIG API Machinery core maintainers) follow this style intentionally for non-legacy reasons, I'd very much like to know why (not trying to be sarcastic there -- I'm genuinely curious as to gaps in CR/CT).  AFAICT, most *new* Go controller projects (both within the kubernetes-sigs umbrella and in the broader community ecosystem) are based on controller-runtime (and several legacy projects have been looking at migrating, IIRC), so significant blockers to further adoption would be super-useful to know.

> It also serves the purpose of test bed for k8s.io/code-generator and other machinery.

I'd argue that that reason isn't sufficient for calling this "sample-controller" -- we shouldn't call this repo *the* sample controller any more than we'd call a controller written without client-go *the* sample controller.  *"Sample" implies "this is a good way to start writing your new controller"*, and I believe we have ample evidence that that's not the case.

It's fine (and a good idea) for us have a testbed for k8s.io/code-generator, but unless we're seriously going to recommend people copy this code to write controllers, then the testbed for k8s.io/code-generator should be "k8s.io/code-generation-test-project" or "k8s.io/code-generator/test-project", or somesuch.
