### ISSUE TITLE
Using sample-controller to create a custom version - it doesn't work

### ISSUE THREAD

**Issue by bhabermaas** [kubernetes/sample-controller#30]
I have created a project to create a custom sample-controller. 
1. I updated pkg/api files to setup Runner and RunnerList types to replace Foo and FooList
2. I created new client code using update-codegen.sh
3. I modified main.go and controller.go appropriately. 

When I build and run I get the following message repeated over and over

E1014 15:31:57.075937   32420 reflector.go:134] github.com/customcontroller/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Runner: no kind "runnerList" is registered for version "customcontroller.k8s.io/v1alpha1" in scheme "github.com/customcontroller/pkg/client/clientset/versioned/scheme/register.go:30"

From this error message can you tell me what I did wrong or give me a hint where I should look ?

**Comment by bhabermaas** [comment]
The significance of modifications to pkg/api has not been adequately documented.

**Comment by liucimin** [comment]
@bhabermaas 
Excuse me.I also get this problem.
Could do  u tell me how can fix this?
