### ISSUE TITLE
Sample controller error syncing 'default/example-foo'

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes/sample-controller#32]
The sample controller is giving me the following error:
error syncing 'default/example-foo': Operation cannot be fulfilled on foos.samplecontroller.k8s.io "example-foo": the object has been modified; please apply your changes to the latest version and try again, requeuing

**Comment by devdattakulkarni** [comment]
@swatisehgal What are the steps that you followed?

**Comment by YunWang** [comment]
@swatisehgal How are you to solve it?

**Comment by nikhita** [comment]
@swatisehgal Can you elaborate on what steps you followed so that we can reproduce this? I think I've seen this reported before as well, so I'd like to solve it.

**Comment by ruiaylin** [comment]
I meet the same problem. @swatisehgal  Do you solve it ?

**Comment by devdattakulkarni** [comment]
@ruiaylin I cannot say what the exact issue is, but one possibility could be that the UpdateFunc for fooInformer needs to be updated to include ResourceVersion check.

Check this PR for the details:
https://github.com/kubernetes/sample-controller/issues/29

Specific changes can be found here:
https://github.com/kubernetes/kubernetes/pull/69749/files
