### ISSUE TITLE
Why I can delete the CRD resource Foo but I can't find the DeleteFunc in FooInformer?

### ISSUE THREAD

**Issue by yhfeng666** [kubernetes/sample-controller#33]
Just as the title shows,I can create the Foo CRD and then create or delete the Foo resource I created after I build the project but I can't find the DeleteFunc in the fooinformer.Informer().AddEventHandler().

**Comment by devdattakulkarni** [comment]
I think the reason this works is client-go machinery might be providing default delete handlers. You can override that by adding a DeleteFunc in AddEventHandler for some special handling.

**Comment by yhfeng666** [comment]
> I think the reason this works is client-go machinery might be providing default delete handlers. You can override that by adding a DeleteFunc in AddEventHandler for some special handling.

@devdattakulkarni Maybe you are true.But I want to know how the controller works when it receives a delete request.
