### ISSUE TITLE
Using sample-controller to create a custom version -but it doesn't work.

### ISSUE THREAD

**Issue by liucimin** [kubernetes/sample-controller#34]
I have created a project to create a custom sample-controller.

I updated pkg/api files to setup KnightNetwork and KnightNetworkList types to replace Foo and FooList
I created new client code using update-codegen.sh
I modified main.go and controller.go appropriately.
When I build and run I get the following message repeated over and over

Listing and watching *v1.KnightNetwork from github.com/knight/pkg/k8s/client/informers/externalversions/factory.go:117
E1126 13:33:58.833083      29 reflector.go:134] github.com/knight/pkg/k8s/client/informers/externalversions/factory.go:117: Failed to list *v1.KnightNetwork: no kind "KnightnetworkList" is registered for version "knight.io/v1" in scheme "github.com/knight/pkg/k8s/client/clientset/versioned/scheme/register.go:30"

From this error message can you tell me what I did wrong or give me a hint where I should look ?

**Comment by nikhita** [comment]
@liucimin Did you also change the `register.go` files to register the `KnightNetwork` and `KnightNetworkList` types?

https://github.com/kubernetes/sample-controller/blob/d17738308fff4926ab017deed4c0fba5bea5629a/pkg/apis/samplecontroller/v1alpha1/register.go#L45-L50

**Comment by liucimin** [comment]
@nikhita  
yes,i have change the register.go.
![image](https://user-images.githubusercontent.com/8232349/49019701-85c80980-f1c9-11e8-8809-7509767728c7.png)

Is there any doc or scripts to show where should we change?

**Comment by liucimin** [comment]
@nikhita 
Thx u.
Maybe i apply a cr use Knightnetwork.
I will change it and try again next day.
Thx for your help~

**Comment by liucimin** [comment]
@nikhita 
I have change all my KnightNetwork  into Knightnetwork. And i work~
I think it because the crd yaml just accept the alphabetic character~
![image](https://user-images.githubusercontent.com/8232349/49057467-a8ded180-f23a-11e8-858d-4e4a496c2baa.png)

so the value in the sample-controller can only use  alphabetic character between words.
Such as:
![image](https://user-images.githubusercontent.com/8232349/49057496-d4fa5280-f23a-11e8-9e81-d11ee6f5717d.png)
