### ISSUE TITLE
Is this outdated?

### ISSUE THREAD

**Issue by rhugga** [kubernetes/sample-controller#41]
I can't for the life of me get this working. I can't even get it to build. So I assume I need godep since I see a Godep directory. (also tried using dep ensure)

I've cloned sample-controller. I change to the sample-controller directory. My GOPATH=/path/to/sample-controller.

`
$pwd
/devel/kubernetes/sample-controller

$go version
go version go1.11.5 darwin/amd64

$godep version 
godep v80 (darwin/amd64/go1.11.5)

/devel/kubernetes/sample-controller $godep get 
godep: [WARNING]: godep should only be used inside a valid go package directory and . 
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.  
godep: [WARNING]:	Current Directory: /devel/kubernetes/sample-controller . 
godep: [WARNING]:	$GOPATH: /devel/kubernetes/sample-controller . 
godep: Unable to find SrcRoot for package .

$echo $GOPATH
/devel/kubernetes/sample-controller
`

What am I doing wrong here. Sorry new to go and its tools.

**Comment by gugahoi** [comment]
https://github.com/tools/godep is not https://github.com/golang/dep

They are different tools so maybe try `dep` instead and try to no use gomodules?

**Comment by codesnk** [comment]
Use "go get k8s.io/sample-controller"

**Comment by nikhita** [comment]
This is not outdated, it works even with the instructions on master. :)

Instructions on using this with go modules can be found here: https://github.com/kubernetes/kubernetes/pull/79081
