### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by biblesyme** [kubernetes/sample-controller#45]
```
go build -o sample-controller .
import cycle not allowed
package k8s.io/sample-controller
        imports flag
        imports errors
        imports runtime
        imports internal/bytealg
        imports internal/cpu
        imports runtime
```

**Comment by btsken** [comment]
I have the same problem.

**Comment by btsken** [comment]
uninstall go as below common
sudo apt-get remove --auto-remove golang-go

and then use this  to install golang
https://golang.org/doc/install

its work for me

**Comment by nikhita** [comment]
Closing since this currently works on master. You can also find instructions on using with go modules here: https://github.com/kubernetes/kubernetes/pull/79081.

Please reopen/comment if you still face the issue.
