### ISSUE TITLE
missing hack/update-vendor.sh

### ISSUE THREAD

**Issue by lionelvillard** [kubernetes/sample-controller#46]
it seems that `go.mod` is generated by `hack/update-vendor.sh` which is missing. Is this intended?

**Comment by nikhita** [comment]
The canonical source of the code in this repo is https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-controller. The code in this repo is a copy of it. 

The script can be found here - https://github.com/kubernetes/kubernetes/blob/master/hack/update-vendor.sh.
