### ISSUE TITLE
Documentation or Support for Go Modules

### ISSUE THREAD

**Issue by christopherhein** [kubernetes/sample-controller#47]
It seems as though `hack/update-codegen.sh` isn't updated properly for using go modules. I was able to patch mine by changing the `CODEGEN_PKG` and removing SCRIPT_ROOT and replacing with:

```
CODEGEN_PKG=${CODEGEN_PKG:-$(ls -d -1 ${GOPATH}pkg/mod/k8s.io/code-generator* 2>/dev/null || echo ../code-generator)}
chmod +x ${CODEGEN_PKG}/generate-groups.sh
```

Is there a better way to handle this? Happy to put in a PR if not.

**Comment by christopherhein** [comment]
Scratch that, I guess I could just use `go mod vendor` and the script works as usual. Closing.

**Comment by christopherhein** [comment]
Reopening since permissions are still set wrong on the file.

**Comment by mattkelly** [comment]
@christopherhein my understanding is that `go mod vendor` alone won't work, as it ignores non-go files. See [this comment](https://github.com/heptio/contour/pull/997#issuecomment-481058718). Maybe you already had a `vendor` dir in place from e.g. `dep`?

I've resorted to using the solution presented in https://github.com/heptio/contour/pull/1010. It's working for me (thanks @glerchundi!), though it's still more complex than I would like it to be. I'm curious how others are using the code generator with go modules.

**Comment by christopherhein** [comment]
I read that comment before I gave it a try and was really surprised when it worked. I'm not sure what I did that was different. At least the `.sh` files were still there. Only thing I needed to do was add my own `boilerplate.go.txt`. I'll investigate a little more and see if I can understand what I did.

**Comment by mattkelly** [comment]
Good call, I had to add a `boilerplate.go.txt` as well.

For completeness: with the latest code-generator package, I also had to remove the `go mod init` from [this script](https://github.com/heptio/contour/pull/1010/files#diff-892d90adfc5482f1fee4517a4ad27aee) since it has become a go module since then.

I'm still fighting with getting Kubernetes dependencies to behave correctly in our move to go modules, but my latest [code generation script](https://github.com/containership/cluster-manager/pull/57/files#diff-5345a009f642e55fc0d5b16d4f5d6f9b) works, for reference.

**Comment by ilansh** [comment]
@mattkelly @christopherhein  
I'm also attempting something similar using your solutions, have you run into an issue where the generated code is not placed in the correct location? i.e. not inside pkg/generated.  
I could probably just move it to the correct location, but I wonder if there's anything else I'm missing.  
Note that I'm running this outside of GOPATH.

**Comment by christopherhein** [comment]
@ilansh did you set the flag `--output-base`  That sets the place or where the package should be found.

https://github.com/kubernetes/sample-controller/blob/master/hack/update-codegen.sh#L31

**Comment by ilansh** [comment]
@christopherhein  Once I did that it simply created the whole repo tree  (github.com/xxx/yyy/...) under the output base.  
without setting `--output-base` the generated files are placed in corresponding location in GOPATH.

**Comment by christopherhein** [comment]
What does your `hack/update-codegen.sh` look like? You might need to adjust your output package path. For example from my project I can run…

```sh
./hack/generate/code-generator/generate-groups.sh \
  client,lister,informer \
  foo/generated \
  awsoperator.io/pkg/apis \
  apigateway:v1alpha1 \
  --output-base $HOME --go-header-file hack/generate/templates/boilerplate.go.txt
ase $HOME --go-header-file hack/generate/templates/boilerplate.go.txt  
```

and this will generate the client libs in `$HOME/foo/generated/`.

**Comment by nikhita** [comment]
> Reopening since permissions are still set wrong on the file.

Created https://github.com/kubernetes/kubernetes/pull/79081

**Comment by damnever** [comment]
It does not put the generated code in right place if the import path for go module isn't same as file path.

For example:

```bash
$ go mod init github.com/u/mymod
$ pwd
/a/b/c/mymod
$ ./generate-groups.sh all github.com/u/mymod/generated github.com/u/pkg/apis "foo:v1" \
  --output-base .
$ ls github.com/u/mymod
generated-files..
```

Here is the dirty fix:
```
$ cd ..
$ mkdir -p github.com/u
$ mv mymod github.com/u
$ cd github.com/u/mymod
$ ./generate-groups.sh all github.com/u/mymod/generated github.com/u/pkg/apis "foo:v1" \
  --output-base ../../../
```

**Comment by nikhita** [comment]
@damnever yup, that's a known issue. Code generation doesn't work with non-GOPATH based assumptions today.

**Comment by damnever** [comment]
@nikhita Maybe code-generator could provide some information as a hit if the path is wrong.
