### ISSUE TITLE
the server could not find the requested resource

### ISSUE THREAD

**Issue by Cindia-blue** [kubernetes/sample-controller#48]
/gopath/src/k8s.io/sample-controller # ./controller -kubeconfig=$HOME/.kube/config
I0416 15:33:06.201192  102295 controller.go:98] Creating event broadcaster
I0416 15:33:06.201399  102295 controller.go:115] Setting up event handlers
I0416 15:33:06.201440  102295 controller.go:156] Starting Foo controller
I0416 15:33:06.201448  102295 controller.go:159] Waiting for informer caches to sync
I0416 15:33:06.202281  102295 reflector.go:128] Starting reflector *v1.Deployment (30s) from k8s.io/client-go/informers/factory.go:133
I0416 15:33:06.202304  102295 reflector.go:166] Listing and watching *v1.Deployment from k8s.io/client-go/informers/factory.go:133
I0416 15:33:06.202287  102295 reflector.go:128] Starting reflector *v1alpha1.Foo (30s) from k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117
I0416 15:33:06.202480  102295 reflector.go:166] Listing and watching *v1alpha1.Foo from k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117
E0416 15:33:06.211787  102295 reflector.go:131] k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Foo: the server could not find the requested resource (get foos.samplecontroller.k8s.io)
I0416 15:33:06.218277  102295 controller.go:369] Processing object: coredns
I0416 15:33:06.218325  102295 controller.go:369] Processing object: calico-kube-controllers
I0416 15:33:06.218336  102295 controller.go:369] Processing object: tiller-deploy
I0416 15:33:07.213361  102295 reflector.go:166] Listing and watching *v1alpha1.Foo from k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117
E0416 15:33:07.215248  102295 reflector.go:131] k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Foo: the server could not find the requested resource (get foos.samplecontroller.k8s.io)
I0416 15:33:08.216289  102295 reflector.go:166] Listing and watching *v1alpha1.Foo from k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117
E0416 15:33:08.218154  102295 reflector.go:131] k8s.io/sample-controller/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Foo: the server could not find the requested resource (get foos.samplecontroller.k8s.io)
^CI0416 15:33:08.251854  102295 shared_informer.go:119] stop requested

/gopath/src/k8s.io/sample-controller # kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by christopherhein** [comment]
Did you `kubectl apply -f artifacts/examples/crd.yaml` first?
