### ISSUE TITLE
Is the `DeleteFunc` useless in the `Informer` event handler register

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/sample-controller#50]
`fooInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{

		AddFunc: controller.enqueueFoo,
		UpdateFunc: func(old, new interface{}) {
			controller.enqueueFoo(new)
		},
})`

I find the resource DELETE will also trigger the `UpdateFunc`, and the periodic resync will triger the `UpdateFunc` either , So I wonder to know is the `DeleteFunc` useless, or anything I missing, thanks

**Comment by devdattakulkarni** [comment]
@vincent-pli You can use DeleteFunc if you need to intercept delete call for some reason.

Here is an example of how we were using DeleteFunc:
https://github.com/cloud-ark/kubeplus/blob/master/operator-manager/controller.go#L168

The operator-manager CRD was being used to deploy Operator Helm charts. With DeleteFunc we registered a handler function that cleaned up various artifacts before deleting the Operator Helm chart.
