### ISSUE TITLE
Object 'Kind' is missing in 'object has no kind field '

### ISSUE THREAD

**Issue by dpaks** [kubernetes/sample-controller#52]
I face this issue while trying to update Foo resource. The error that it throws makes sense as the object from informer store doesn't have TypeMeta filled.

> &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:example-foo GenerateName: Namespace:default SelfLink:/apis/samplecontroller.k8s.io/v1alpha1/namespaces/default/foos/example-foo UID:a8a7a387-83c1-11e9-b13f-002590947496 ResourceVersion:214806 Generation:1 CreationTimestamp:2019-05-31 16:32:19 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[]} Spec:{DeploymentName:example-foo Replicas:0xc420530ef0} Status:{AvailableReplicas:0}}

Hence, I cannot update status for Foo resource.
Can someone help me in this regard?

**Comment by devdattakulkarni** [comment]
@dpaks Can you outline the exact steps that you followed?
