### ISSUE TITLE
Running update-codegen.sh results into error unsupported type.

### ISSUE THREAD

**Issue by gautamkmr** [kubernetes/sample-controller#55]
88e9fe562973:sample-controller gauta$ ./hack/update-codegen.sh 
go: downloading k8s.io/gengo v0.0.0-20190116091435-f8a0810f38af
go: extracting k8s.io/gengo v0.0.0-20190116091435-f8a0810f38af
Generating deepcopy funcs
F0615 15:31:22.971465   29579 deepcopy.go:873] Hit an unsupported type invalid type.

**Comment by nikhita** [comment]
@gautamkmr Was this on the sample-controller master? `88e9fe562973` doesn't seem to reference any commit, were there any extra changes? If so, could you list them here?

**Comment by gautamkmr** [comment]
@nikhita Thanks for reply, yes this is on master branch.

88e9fe562973 is my host :) sorry for confusion.

I was following the steps from here which is pretty generic, https://itnext.io/building-an-operator-for-kubernetes-with-the-sample-controller-b4204be9ad56

Instead of running `go get `I manually cloned the master branch

**Comment by nikhita** [comment]
Looks like the issue is https://github.com/kubernetes/kubernetes/issues/79149 :)
