### ISSUE TITLE
Using golang 1.12+

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/sample-controller#56]
If you are using golang 1.12 and up, which supports go modules, you don't need to have the project in your GOPATH. 

Here are the steps that you can follow for trying out the project with golang 1.12+

git clone https://github.com/kubernetes/sample-controller.git
cd sample-controller/
go mod vendor
go build -o sample-controller .
./sample-controller -kubeconfig=$HOME/.kube/config

**Comment by nikhita** [comment]
@devdattakulkarni Thanks! Closing since it'll be covered in https://github.com/kubernetes/kubernetes/pull/79081

**Comment by devdattakulkarni** [comment]
@nikhita 👍
