### ISSUE TITLE
The folder "pkg/generated" not being generated

### ISSUE THREAD

**Issue by keshiha96** [kubernetes/sample-controller#62]
When building the sample-controller from scratch, and executing the command `./hack/update-codegen.sh` it does not generate the **generated** directory under **pkg** folder. 

When commenting out the line `--output-base "$(dirname "${BASH_SOURCE[0]}")/../../.." \` only it generates the directories. 

But **zz_generated.deepcopy.go** file is not generated under **pkg/apis/samplecontroller/v1alpha1** directory. How to generate it automatically?

**Comment by lenardchristopher** [comment]
@keshiha96 How did you solve this?
