### ISSUE TITLE
[question] AddRateLimited or Add directly

### ISSUE THREAD

**Issue by gaocegege** [kubernetes/sample-controller#63]
Hi I have a question about the usage of workqueue in the sample controller.

We are using workqueue.RateLimitingInterface as the work queue, but we only use AddRateLimited in [`processNextWorkItem`](https://github.com/kubernetes/sample-controller/blob/master/controller.go#L221).

```diff
		// Run the syncHandler, passing it the namespace/name string of the
		// Foo resource to be synced.
		if err := c.syncHandler(key); err != nil {
			// Put the item back on the workqueue to handle any transient errors.
+			c.workqueue.AddRateLimited(key)
			return fmt.Errorf("error syncing '%s': %s, requeuing", key, err.Error())
		}
```

In [`enqueueFoo`](https://github.com/kubernetes/sample-controller/blob/master/controller.go#L344), we use Add instead. Is there any convention about it?

```diff
// enqueueFoo takes a Foo resource and converts it into a namespace/name
// string which is then put onto the work queue. This method should *not* be
// passed resources of any type other than Foo.
func (c *Controller) enqueueFoo(obj interface{}) {
	var key string
	var err error
	if key, err = cache.MetaNamespaceKeyFunc(obj); err != nil {
		utilruntime.HandleError(err)
		return
	}
+	c.workqueue.Add(key)
}
```

**Comment by YesterdayxD** [comment]
I think the reason is that only it exists error , call c.workqueue.AddRateLimited(key) .
```
// Put the item back on the workqueue to handle any transient errors.
```
But if it exists any informer update, call enqueueFoo.Don't need error occurs.
