### ISSUE TITLE
[Question] How to version the CRDs ?

### ISSUE THREAD

**Issue by alok87** [kubernetes/sample-controller#68]
Doc - https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

For adding a version say v1beta1 and v1, should i keep copies of the v1apha1 folders or rename them. Renaming them won't keep things backward compatible.

**Comment by devdattakulkarni** [comment]
In your controller code you should keep all the versions (v1alpha1, v1beta1, v1) as long as you plan to support them. You will want to follow some deprecation policy for removing previous versions and inform your users well ahead of time when the support for previous versions will be removed from your controller.
