### ISSUE TITLE
Issue with informer factory list interface

### ISSUE THREAD

**Issue by suneeta-mall** [kubernetes/sample-controller#7]
I am trying to create a Kubernetes controller inline with how sample-controller is built. But I keep getting this 
```
ERROR: logging before flag.Parse: E0123 13:59:00.293146   57870 reflector.go:205] .....gok8s/client/informers/externalversions/factory.go:73: Failed to list *v1.ContainerVersion: returned object must be a list: object does not implement the List interfaces
```
but the runtime objects are correctly generated using https://github.com/kubernetes/code-generator with same version branch and structure of objects seems to be same.  

I know this is a outside the scope of sample-controller but I have seen sample-controller giving same error but cant reproduce it with sample controller anymore.
Now I get this error on sample controller:

```
➜  sample-controller git:(master) sample-controller --kubeconfig ~/.kube/config                          
E0123 13:25:34.768384   53728 controller.go:236] error syncing 'default/example-foo': Operation cannot be fulfilled on foos.samplecontroller.k8s.io "example-foo": the object has been modified; please apply your changes to the latest version and try again
```

I am on k8s 1.9.2 and I have regenerated and verified that runtime objects of sample controller are correct as per 1.9.2. Why is the sample controller giving this error?

**Comment by suneeta-mall** [comment]
Not quite a bug .. false alarm ..

**Comment by irfn** [comment]
@suneeta-mall can you explain a little bit on how it was resolved

**Comment by qwe5456** [comment]
Hi @suneeta-mall , I came into the exactly the same error when implementing my own controller. I was also following the sample-controller example. Could you please provide some information on how you resolved this error? Thank you!

**Comment by suneeta-mall** [comment]
@qwe5456, It was the problem with the runtime objects generated by code-generator in my case. I had open api tags (from memory) which was the cause of the 'bad' objects getting generated ..   Removing that tag from the custom objects and regenerating the runtime objects fixed the issue ..

**Comment by qwe5456** [comment]
@suneeta-mall thank you for your quick response. I'll look into my code accordingly.

**Comment by zikes** [comment]
I also got this error when I accidentally used `metav1.ObjectMeta` in my `FooList` struct instead of `metav1.ListMeta`.

**Comment by inkinworld** [comment]
> I also got this error when I accidentally used `metav1.ObjectMeta` in my `FooList` struct instead of `metav1.ListMeta`.

thx, you save my day~

**Comment by wm775825** [comment]
> I also got this error when I accidentally used `metav1.ObjectMeta` in my `FooList` struct instead of `metav1.ListMeta`.

Very very thanks!

**Comment by daimaxiaxie** [comment]
@zikes  thanks. I have same error. It is difficult to find.
