### ISSUE TITLE
Is this project  limited by version of golang?

### ISSUE THREAD

**Issue by chenbaoding2818** [kubernetes/sample-controller#70]
My golang is version 1.11 but buil this project is failed 
Should remind everyone in README.md when we build this project should use version 1.13 of golang？

**Comment by chenbaoding2818** [comment]
# k8s.io/apimachinery/pkg/util/errors
../mygo/pkg/mod/k8s.io/apimachinery@v0.0.0-20200410021338-ff54c5b023af/pkg/util/errors/errors.go:99:10: undefined: errors.Is
note: module requires Go 1.13

**Comment by caoruidong** [comment]
Yes, its dependence uses new error handling in Go 1.13
