### ISSUE TITLE
Execute  generate-groups.sh is  failure

### ISSUE THREAD

**Issue by wxuedong** [kubernetes/sample-controller#77]
@Hi ，execute the file `./hack/update-codegen.sh` locally and it prompts an error，

bash: ../code-generator/generate-groups.sh: No such file or directory

go version is 1.16.3

**Comment by rumstead** [comment]
Make sure this is added to your project, https://github.com/kubernetes/sample-controller/blob/master/hack/tools.go. Additionally, make sure you have tools added as [go build tag](https://golang.org/pkg/go/build/)

**Comment by hippoKnight** [comment]
@wxuedong, have you run `go mod vendor` (in *Fetch sample-controller and its dependencies* in README.md) ?
