### ISSUE TITLE
code-generator depends on APIMachinery registration package, fails to update generated code

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/sample-controller#8]
Updating the generated clientsets (after manually vendoring `k8s.io/code-generator` due to #6) fails because the client-gen's default input directories include `k8s.io/apimachinery/pkg/apimachinery/registered`, which is not vendored in this repository.  AFAICT, it doesn't need to be vendored in this repository (since it's just for API server registration), so it should probably be an optional input directory, not a default one.  I can cross-file to k8s.io/code-generator if necessary.

**Comment by DirectXMan12** [comment]
cc @sallyom

**Comment by sttts** [comment]
@DirectXMan12 https://github.com/kubernetes/kubernetes/pull/57143 fixes this. Needs a review.
