### ISSUE TITLE
README is wrong on generating code when using Go modules

### ISSUE THREAD

**Issue by ecejjar** [kubernetes/sample-controller#81]
The README.md file reads, when discussing code generation using Go 1.11 modules:

"When using go 1.11 modules (GO111MODULE=on), issue the following commands --- **starting in whatever working directory you like**."

However, when calling the code generator (downloaded e.g. using `go mod vendor`), it expects your code to be in the proper Go package path:
```
jjarauz@javier-XPS:~/git/ccpcontroller$ ./hack/update-codegen.sh
Generating deepcopy funcs
F0920 10:49:58.455671 2562719 main.go:80] Error: Failed executing generator: some packages had errors:
errors in package "github.com/ecejjar/ccpcontroller/pkg/apis/ccpcontroller/v1alpha1":
open ../../../github.com/ecejjar/ccpcontroller/pkg/apis/ccpcontroller/v1alpha1/zz_generated.deepcopy.go: no such file or directory
```

So , you can't start in whatever working directory you like; you **must** clone your code in a Go package-like path.

**Comment by akhil-rane** [comment]
I am getting the same issue, not able to generate code when working directory is outside GOPATH
