### ISSUE TITLE
go build with error sf.IsExported undefined

### ISSUE THREAD

**Issue by molinjun** [kubernetes/sample-controller#84]
I pulled the latest version and go build. There is some issues:
```bash
$ go build -o sample-controller .
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
I googled and someone mentioned it should update the go version from go 1.16 to go 1.17. I am not sure if this is the issue.

**Comment by blueriver1125** [comment]
+1

**Comment by gedennis** [comment]
@blueriver1125 could you like to share your go.mod.
Why does the repo use a wrong version?

**Comment by blueriver1125** [comment]
> 

module example.com/example-broker

go 1.16

require (
	github.com/gin-gonic/gin v1.7.7
	github.com/kubernetes-sigs/service-catalog v0.3.1
	k8s.io/apimachinery v0.19.0
	k8s.io/client-go v0.19.0
)
