### ISSUE TITLE
Generate the code with update-codegen.sh in a wrong path

### ISSUE THREAD

**Issue by molinjun** [kubernetes/sample-controller#86]
When I generate the code with update-codegen with a go mod way, the generated code is located in a wrong path.
Reproduce action:
```bash
# git download the repo and cd in there
# remove the generated code before, deepcopy file and folder pkg/genereated
$ go mod tidy & go mod vendor
$ ./hack/update-codegen.sh
```
the code is in a wrong path, so update the default update-codegen.sh output-base
```shell
bash "${CODEGEN_PKG}"/generate-groups.sh "deepcopy,client,informer,lister" \
  k8s.io/sample-controller/pkg/generated k8s.io/sample-controller/pkg/apis \
  samplecontroller:v1alpha1 \
  --output-base "$(dirname "${BASH_SOURCE[0]}")/.." \
  --go-header-file "${SCRIPT_ROOT}"/hack/boilerplate.go.txt
```
then the generated code is in a k8s.io folder in the sample-controller repo.
What did I miss?

**Comment by dirathea** [comment]
Hey, @molinjun Maybe [this thread](https://kubernetes.slack.com/archives/C0EG7JC6T/p1638401250349400?thread_ts=1638387450.345100&cid=C0EG7JC6T) helps you.

Basically, this is a mirror of small parts from kubernetes/kubernetes and will work perfectly on that setup. For me, I solve this issue by placing the repo on its desired states, which under `k8s.io` directory.

```bash
git clone https://github.com/kubernetes/sample-controller.git k8s.io/sample-controller
```

Hope this helps, cheers!
