### ISSUE TITLE
How is the Deep Copy files are generated ?

### ISSUE THREAD

**Issue by RameshRM** [kubernetes/sample-controller#89]
I have cloned this repository, and tried to run `./hack/update-codegen.sh` the script is not generating the `deepcopy` related files, what am i missing ? 

> `go version go1.19.5 darwin/amd64` is the go version

**Comment by fulviodenza** [comment]
Different repo but same problem:
I solved running `go mod vendor` in the repo, modified the script as you can see in the repo https://github.com/fulviodenza/sample-apiserver and then moving the right files in the right folders. Unfortunately this was the only method I found.
