### ISSUE TITLE
README instructions gives an error while trying to run the controller

### ISSUE THREAD

**Issue by hvishwanath** [kubernetes/sample-controller#9]
I am just following the instructions in README. I see the following error:

```
$ go run *.go -kubeconfig=$HOME/.kube/config                                                 
E0129 22:06:44.562026    1469 reflector.go:205] github.com/hvishwanath/sample-controller/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Deployment: the server could not find the requested resource
E0129 22:06:45.578094    1469 reflector.go:205] github.com/hvishwanath/sample-controller/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Deployment: the server could not find the requested resource
E0129 22:06:46.620581    1469 reflector.go:205] github.com/hvishwanath/sample-controller/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Deployment: the server could not find the requested resource
```

**Comment by nikhita** [comment]
@hvishwanath Not able to reproduce this. Are you on the latest master?

/cc @sttts @munnerz

**Comment by sttts** [comment]
`kubectl version` would help

**Comment by hvishwanath** [comment]
```
$ kubectl version                                                                                             
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sttts** [comment]
/assign @munnerz 

I guess the controller won't work before 1.8 or even 1.9 (it did not even exist before 1.9).

**Comment by munnerz** [comment]
Yep this will be down to the recent PR that switched sample-controller to
use apps/v1 instead of v1beta1. As apps/v1 did not exist until 1.9, we no
longer support anything earlier. Perhaps changing back to v1beta1 or
v1beta2 would be a better idea?

**Comment by hvishwanath** [comment]
Or may be check for the server version and use the right API object?

**Comment by sttts** [comment]
> Perhaps changing back to v1beta1 or v1beta2 would be a better idea?

We should just document the minimal requirements.

**Comment by nikhita** [comment]
> We should just document the minimal requirements.

+1. apps/v1 is GA so we should use it.

> Or may be check for the server version and use the right API object?

While this makes sense, sample-controller is supposed to be an example and complicating the example doesn't seem like a good idea. Given that people mostly end up copy-pasting this repo...

**Comment by hvishwanath** [comment]
I think it may be worthwhile to do k8s version based clientset api calls, given that k8s 1.7.x has support for CRDs and controllers can be written. For instance `client-python` works fine with 1.7.x.

**Comment by sttts** [comment]
I agree with @nikhita that we shouldn't try to support multiple versions in this example, especially not with a GA type.

**Comment by nikhita** [comment]
@hvishwanath Sorry for getting back so late on this but the `release-1.9` branch does not use `apps/v1` so that branch should work fine with previous versions. 

(Mentioning this here since it might useful for anyone who comes across this)
