### ISSUE TITLE
无法执行生成

### ISSUE THREAD

**Issue by weiqiangxu** [kubernetes/sample-controller#91]
./hack/update-codegen.sh
./hack/update-codegen.sh: 行 24: ../code-generator/kube_codegen.sh: No such file or directory

**Comment by godblesslancek** [comment]
Hello, I personally solved it by git cloning the code-generator repository https://github.com/kubernetes/code-generator  in the root directory of the repo. I also cd into hack before executing ./update-codegen.sh. If I don't do so, I encounter problems because the script doesn't expect that you execute it in the root directory.

**Comment by googs1025** [comment]
Hey bro, you need to check if there is this file in the directory, or don't execute this script from the root directory, you need to execute it in the project directory

**Comment by quartzeast** [comment]
switch to a newer branch, like `release-1.27`, and run `go mod vendor`, and then in your project root run `chmod +x./vendor/k8s.io/code-generator/generate-groups.sh`, Add executable permissions to the script, and finally run `./hack/update-codegen.sh` in the project root

**Comment by silentred** [comment]
> switch to a newer branch, like `release-1.27`, and run `go mod vendor`, and then in your project root run `chmod +x ./vendor/k8s.io/code-generator/generate-groups.sh`, Add executable permissions to the script, and finally run `./hack/update-codegen.sh` in the project root

It works for me. Thanks.

**Comment by silentred** [comment]
> switch to a newer branch, like `release-1.27`, and run `go mod vendor`, and then in your project root run `chmod +x ./vendor/k8s.io/code-generator/generate-groups.sh`, Add executable permissions to the script, and finally run `./hack/update-codegen.sh` in the project root

I followed the steps above. The `./hack/update-codegen.sh` command generated codes out side of my project. My project is at `/Users/jason/Desktop/projects/sample-controller`, however the generated code is at `/Users/jason/Desktop/` 

![image](https://github.com/kubernetes/sample-controller/assets/3345293/a059ecfb-5935-445e-a4bf-922a74e86198)
